spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
jwt:
  token:
    secretKey: ${JWT_SECRETKEY}
    expiration: # (만료) 시간 설정은 ms단위
      access: 14400000 # 4시간(보통 1시간~4시간 단위를 많이 채택)
      refresh: 604800 # 7일
cloud:
  aws:
    s3:
      bucket: dnbn-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accesskey: ${AWS_ACCESS_KEY}
      secretkey: ${AWS_SECRET_KEY}

